# Application properties: configure datasource, Hibernate, Flyway and logging `r`nspring.application.name=giardini


# SETUP MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestionale_giardiniere?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


# SETUP HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
                                            #opzioni possibili rispetto all'azione di hibernate sul db
                                            #create -> hibernate crea lo schema del db (DDL)  ogni volta che l'applicazione viene avviata -> CREA e DISTRUGGE ad ogni avvio
                                            #update -> aggiorna il db in base alle modifiche apportate alle entitÃ  lato Java -> RICREA se ci sono aggiornamenti
                                            #none -> non agisce sullo schema del db
                                            #create-drop -> crea il db all'avvio e lo elimina quando l'applicazione viene chiusa
                                            #validate -> valida lo schema delle entitÃ , quello che legge lato java senza apportare modifiche, controlla che la struttura  del db
                                            #sia coerente con le classi java

spring.jpa.show-sql=true
                            #mostra le query sql in console

spring.jpa.properties.hibernate.format-sql=true
                            #formatta le query con l'indentazione corretta in console, serve solo per la visualizzazione in console



# SETUP FLYWAY
spring.flyway.enabled=true
                            # Abilita Flyway, eseguendo automaticamente le migrazioni del database all'avvio dell'applicazione.

spring.flyway.locations=classpath:db/migration
                                                # Specifica la cartella del progetto contenente gli script SQL di migrazione.



# SETUP DEBUG
logging.level.org.hibernate.SQL=DEBUG
                                        # DEBUG:    Ã¨ un livello di log per cui vengono stampate info dettagliate nel file log sulle query
                                        # INFO:     stampa solo informazioni generali sul funzionamento dell'applicazione.
                                        # WARN:     stampa solo avvisi che segnalano situazioni anomale ma non bloccanti.
                                        # ERROR:    stampa solo errori che hanno causato il fallimento di un'operazione.

logging.level.org.hibernate.orm.jdbc.bind=TRACE
                                                #info dettagliate sui parametri delle query, serve a vedere i valori reali sostituiti nei placeholder (?) delle query SQL.
                                                
logging.file.path=logs
                        #setto il percorso per il file di log







# !!!! CONFIGURAZIONI CUSTOM CON DESCRIZIONE: li metto poi prima di attivarli cerchiamo di capire anche assieme con chatGpt come gestirli...
            # Intanto li metto cosi se possono servire sono giÃ  qua da attivare, ma in realtÃ  apparte il primo che possiamo comuque perÃ² gestire con i rest controller sono tutti quasi inutili



#Per port inserire tag nascosti con metodi 'patch' e 'delete' da poter implementare nei form
#spring.mvc.hiddenmethod.filter.enabled=true


#indico ad hibernate che uso il dialetto di mysql in questo modo saprÃ  come impostare corretamente le sintassi associata
#per le DML,DLL e DQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# QUESTA in realtÃ  dovrebbe essere obsoleta(giÃ  implicita con dipendenza mysql driver)


#per dare un nome al file di log
#logging.file.name=logs/libreria.log
